CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(200) NOT NULL,
	`businessType` varchar(100) NOT NULL,
	`city` varchar(100) NOT NULL,
	`district` varchar(100),
	`zoneId` int,
	`zoneName` varchar(100),
	`verifiedPhone` varchar(20),
	`website` varchar(500),
	`googleMapsUrl` varchar(1000),
	`instagramUrl` varchar(500),
	`twitterUrl` varchar(500),
	`snapchatUrl` varchar(500),
	`tiktokUrl` varchar(500),
	`facebookUrl` varchar(500),
	`reviewCount` int DEFAULT 0,
	`brandingQualityScore` float,
	`seasonalReadinessScore` float,
	`leadPriorityScore` float,
	`biggestMarketingGap` text,
	`revenueOpportunity` text,
	`suggestedSalesEntryAngle` text,
	`analysisStatus` enum('pending','analyzing','completed','failed') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `social_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`platform` enum('instagram','twitter','snapchat','tiktok','facebook') NOT NULL,
	`profileUrl` varchar(500),
	`hasAccount` boolean DEFAULT false,
	`postingFrequencyScore` float,
	`engagementScore` float,
	`contentQualityScore` float,
	`hasSeasonalContent` boolean DEFAULT false,
	`hasPricingContent` boolean DEFAULT false,
	`hasCallToAction` boolean DEFAULT false,
	`contentStrategyScore` float,
	`digitalPresenceScore` float,
	`gaps` json,
	`overallScore` float,
	`summary` text,
	`recommendations` json,
	`rawAnalysis` text,
	`analyzedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `social_analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `website_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`url` varchar(500) NOT NULL,
	`hasWebsite` boolean DEFAULT false,
	`loadSpeedScore` float,
	`mobileExperienceScore` float,
	`seoScore` float,
	`contentQualityScore` float,
	`designScore` float,
	`offerClarityScore` float,
	`hasSeasonalPage` boolean DEFAULT false,
	`hasOnlineBooking` boolean DEFAULT false,
	`hasPaymentOptions` boolean DEFAULT false,
	`hasDeliveryInfo` boolean DEFAULT false,
	`technicalGaps` json,
	`contentGaps` json,
	`overallScore` float,
	`summary` text,
	`recommendations` json,
	`rawAnalysis` text,
	`analyzedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `website_analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `zones` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameEn` varchar(100),
	`region` varchar(100) NOT NULL,
	`status` enum('not_started','in_progress','completed') NOT NULL DEFAULT 'not_started',
	`leadsCount` int NOT NULL DEFAULT 0,
	`targetLeads` int NOT NULL DEFAULT 20,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `zones_id` PRIMARY KEY(`id`)
);
