CREATE TABLE `real_social_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`tiktokUsername` varchar(100),
	`tiktokFollowers` int,
	`tiktokFollowing` int,
	`tiktokHearts` bigint,
	`tiktokVideoCount` int,
	`tiktokVerified` boolean DEFAULT false,
	`tiktokEngagementRate` float,
	`tiktokDescription` text,
	`tiktokTopVideos` json,
	`twitterUsername` varchar(100),
	`twitterFollowers` int,
	`twitterFollowing` int,
	`twitterTweetsCount` int,
	`twitterVerified` boolean DEFAULT false,
	`twitterBlueVerified` boolean DEFAULT false,
	`twitterDescription` text,
	`twitterLocation` varchar(200),
	`instagramUsername` varchar(100),
	`instagramFollowers` int,
	`instagramFollowing` int,
	`instagramPostsCount` int,
	`instagramVerified` boolean DEFAULT false,
	`instagramEngagementRate` float,
	`instagramBio` text,
	`instagramTopPosts` json,
	`backlinkDomain` varchar(200),
	`backlinkTotal` int DEFAULT 0,
	`backlinkReferringDomains` json,
	`backlinkHasGMB` boolean DEFAULT false,
	`backlinkHasSocial` boolean DEFAULT false,
	`availableSources` json,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `real_social_snapshots_id` PRIMARY KEY(`id`)
);
