export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  googlePagespeedApiKey: process.env.GOOGLE_PAGESPEED_API_KEY ?? "",
  googleCustomSearchApiKey: process.env.GOOGLE_CUSTOM_SEARCH_API_KEY ?? "",
  googleCustomSearchEngineId: process.env.GOOGLE_CUSTOM_SEARCH_ENGINE_ID ?? "",
  // Bright Data
  brightDataWsEndpoint: process.env.BRIGHT_DATA_WS_ENDPOINT ?? "",
  brightDataApiToken: process.env.BRIGHT_DATA_API_TOKEN ?? "",
  brightDataSerpHost: process.env.BRIGHT_DATA_SERP_HOST ?? "brd.superproxy.io",
  brightDataSerpPort: parseInt(process.env.BRIGHT_DATA_SERP_PORT ?? "33335"),
  brightDataSerpUsername: process.env.BRIGHT_DATA_SERP_USERNAME ?? "",
  brightDataSerpPassword: process.env.BRIGHT_DATA_SERP_PASSWORD ?? "",
};
